export const baseUrl = {
    Sing_UP: "https://api.bentoapp.ca/backend/user/signup/parent/normal?",
    login: 'https://api.bentoapp.ca/backend/user/login/normal?',
    getAllIngredients: 'https://api.bentoapp.ca/backend/ingredient/get',
    matchUnmatchIngredients: 'https://api.bentoapp.ca/backend/recipe/search-by-ingredient?ingredients=',
    getShoppingList :'https://api.bentoapp.ca/backend/pantry/get-items/',
    addShoppingList :'https://api.bentoapp.ca/backend/pantry/add-item/',
    removeShoppingList:'https://api.bentoapp.ca/backend/pantry/delete-item/',
    addLunchBox:'https://api.bentoapp.ca/backend/lunchbox/add/',
    getLunchBox:'https://api.bentoapp.ca/backend/lunchbox/get/',
    addKid:'https://api.bentoapp.ca/backend/user/kid/creation?',
    getKid:'https://api.bentoapp.ca/backend/user/kid?',
    forgotPassword:'https://api.bentoapp.ca/backend/user/reset/password?',
    assignKid:'https://api.bentoapp.ca/backend/lunchbox/assign-kid-lunchbox/',
    getAssignKid:'https://api.bentoapp.ca/backend/lunchbox/get-assign-kid/',
    addRating:'https://api.bentoapp.ca/backend/rating/recipe/636cc5218bcff7669137eeb5?',
    getRating:'https://api.bentoapp.ca/backend/rating/get-rating/?',
    updateProfile:'https://api.bentoapp.ca/backend/user/update-profile/',
    deleteKid:'https://api.bentoapp.ca/backend/user/delete-kid-profile?',

}